export default {
    LOGIN: 'LOGIN',

    GET_POINTS: 'GET_POINTS',
    GET_ALL_POINTS: 'GET_ALL_POINTS',
    ADD_POINT: 'ADD_POINT',
    UPDATE_POINT: 'UPDATE_POINT',
    
    GET_SUBJECTS: 'GET_SUBJECTS',
    GET_ALL_SUBJECTS: 'GET_ALL_SUBJECTS',
    ADD_SUBJECT: 'ADD_SUBJECT',
    UPDATE_SUBJECT: 'UPDATE_SUBJECT',

    ADD_USER: 'ADD_USER',
    UPDATE_USER: 'UPDATE_USER',
    FORBID_USER: 'FORBID_USER',
    MODIFY_USER: 'MODIFY_USER',
}