export default {
    LOGIN: 'LOGIN',

    GET_POINTS: 'GET_POINTS',
    GET_ALL_POINTS: 'GET_ALL_POINTS',
    ADD_POINT: 'ADD_POINT',
    UPDATE_POINT: 'UPDATE_POINT',
    
    GET_SUBJECTS: 'GET_SUBJECTS',
    GET_ALL_SUBJECTS: 'GET_ALL_SUBJECTS',
    ADD_SUBJECT: 'ADD_SUBJECT',
    UPDATE_SUBJECT: 'UPDATE_SUBJECT',

    ADD_USER: 'ADD_USER',
    UPDATE_USER: 'UPDATE_USER',
    FORBID_USER: 'FORBID_USER',
    MODIFY_USER: 'MODIFY_USER',

    ADD_PROBLEM: 'ADD_PROBLEM',
    GET_ALL_PROBLEM: 'GET_ALL_PROBLEM',
    VIEW_PROBLEM: 'VIEW_PROBLEM',
    DROP_PROBLEM: 'DROP_PROBLEM',
    MODIFY_PROBLEM: 'MODIFY_PROBLEM',

    DETAILS_PAPER: 'DETAILS_PAPER',
    PAPER_LIST: 'PAPER_LIST',
    MODIFY_PAPER: 'MODIFY_PAPER'
}